FROM golang:1.22-alpine AS builder
WORKDIR /auth
ENV GOTOOLCHAIN=local
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o auth cmd/auth/main.go

FROM alpine:3.19
WORKDIR /auth
COPY --from=builder /auth/auth .
EXPOSE 8081
CMD ["./auth"]