FROM golang:1.23-alpine AS builder
WORKDIR /notifier
ENV GOTOOLCHAIN=local
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o notifier cmd/notifier/main.go

FROM alpine:3.19
WORKDIR /notifier
COPY --from=builder /notifier/notifier .
EXPOSE 8083
CMD ["./notifier"]